# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  api:
    taskfile: ./apps/api/Taskfile.yaml
    dir: ./apps/api
  web:
    taskfile: ./apps/web/Taskfile.yaml
    dir: ./apps/web
  project:
    taskfile: ./taskfiles/project.yaml
    flatten: true
  hooks:
    taskfile: ./taskfiles/hooks.yaml
    flatten: true

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  commit:lint:
    desc: Lint the latest commit message
    cmds:
      - pnpm exec commitlint --config ./commitlint.config.cjs --last
