-- +goose Up
CREATE SCHEMA identity;
CREATE SCHEMA directory;

-- +goose StatementBegin
CREATE FUNCTION identity.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TABLE identity.users (
    id uuid PRIMARY KEY DEFAULT uuidv7(), -- UUIDv7 user primary key generated by PostgreSQL.
    email text NOT NULL, -- Trimmed lowercase login and notification email.
    username text COLLATE "C" NOT NULL, -- Globally unique lowercase public username.
    display_name text NOT NULL, -- User-facing display name not used for identity matching.
    password_hash text, -- Reserved optional password verifier for future password login.
    role text NOT NULL DEFAULT 'USER', -- Base authorization role: USER, ADMIN, or SYS_ADMIN.
    status text NOT NULL DEFAULT 'ACTIVE', -- Account lifecycle state: ACTIVE, SUSPENDED, or REMOVED.
    email_verified_at timestamptz, -- Time the current email address was verified.
    auth_version integer NOT NULL DEFAULT 1, -- Version incremented to invalidate active authentication sessions.
    profile jsonb NOT NULL DEFAULT '{}'::jsonb, -- Public descriptive profile properties validated by the API.
    settings jsonb NOT NULL DEFAULT '{}'::jsonb, -- Private user preferences validated by the API.
    last_login_at timestamptz, -- Most recent successful authentication time.
    created_at timestamptz NOT NULL DEFAULT now(), -- Account creation time.
    updated_at timestamptz NOT NULL DEFAULT now(), -- Last account or profile update time maintained by trigger.
    CONSTRAINT users_email_normalized_check CHECK (email = lower(btrim(email)) AND email <> ''),
    CONSTRAINT users_username_check CHECK (username ~ '^[a-z0-9_]{3,32}$'),
    CONSTRAINT users_display_name_check CHECK (btrim(display_name) <> ''),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN', 'SYS_ADMIN')),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'REMOVED')),
    CONSTRAINT users_auth_version_check CHECK (auth_version >= 1),
    CONSTRAINT users_profile_object_check CHECK (jsonb_typeof(profile) = 'object'),
    CONSTRAINT users_settings_object_check CHECK (jsonb_typeof(settings) = 'object'),
    CONSTRAINT users_email_verified_at_check CHECK (email_verified_at IS NULL OR email_verified_at >= created_at),
    CONSTRAINT users_last_login_at_check CHECK (last_login_at IS NULL OR last_login_at >= created_at)
);

CREATE UNIQUE INDEX users_email_unique_idx ON identity.users (email);
CREATE UNIQUE INDEX users_username_unique_idx ON identity.users (username);
CREATE INDEX users_role_status_idx ON identity.users (role, status);
CREATE TRIGGER users_touch_updated_at
BEFORE UPDATE ON identity.users
FOR EACH ROW EXECUTE FUNCTION identity.touch_updated_at();

CREATE TABLE identity.oauth_identities (
    id uuid PRIMARY KEY DEFAULT uuidv7(), -- UUIDv7 OAuth identity primary key.
    user_id uuid NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE, -- Owning local user account.
    provider text NOT NULL, -- External authentication provider currently limited to GITHUB.
    provider_user_id text NOT NULL, -- Stable provider-side subject identifier.
    provider_login text, -- Latest provider username or login for display.
    profile jsonb NOT NULL DEFAULT '{}'::jsonb, -- Last normalized public provider profile snapshot.
    created_at timestamptz NOT NULL DEFAULT now(), -- Time the provider identity was linked.
    updated_at timestamptz NOT NULL DEFAULT now(), -- Last provider identity refresh time.
    CONSTRAINT oauth_identities_provider_check CHECK (provider = 'GITHUB'),
    CONSTRAINT oauth_identities_provider_user_id_check CHECK (btrim(provider_user_id) <> ''),
    CONSTRAINT oauth_identities_provider_login_check CHECK (provider_login IS NULL OR btrim(provider_login) <> ''),
    CONSTRAINT oauth_identities_profile_object_check CHECK (jsonb_typeof(profile) = 'object'),
    CONSTRAINT oauth_identities_provider_subject_unique UNIQUE (provider, provider_user_id),
    CONSTRAINT oauth_identities_user_provider_unique UNIQUE (user_id, provider)
);

CREATE TRIGGER oauth_identities_touch_updated_at
BEFORE UPDATE ON identity.oauth_identities
FOR EACH ROW EXECUTE FUNCTION identity.touch_updated_at();

COMMENT ON SCHEMA identity IS 'Authoritative user accounts and OAuth login identities.';
COMMENT ON SCHEMA directory IS 'Authoritative site directory records and typed AGE graph access functions.';
COMMENT ON FUNCTION identity.touch_updated_at() IS 'Maintains updated_at on identity rows before update.';
COMMENT ON TABLE identity.users IS 'User account and profile root with lifecycle represented by status.';
COMMENT ON TABLE identity.oauth_identities IS 'GitHub OAuth login identities without provider access or refresh tokens.';
COMMENT ON TRIGGER users_touch_updated_at ON identity.users IS 'Maintains the user updated_at timestamp.';
COMMENT ON TRIGGER oauth_identities_touch_updated_at ON identity.oauth_identities IS 'Maintains the OAuth identity updated_at timestamp.';

COMMENT ON COLUMN identity.users.id IS 'UUIDv7 user primary key generated by PostgreSQL.';
COMMENT ON COLUMN identity.users.email IS 'Trimmed lowercase login and notification email.';
COMMENT ON COLUMN identity.users.username IS 'Globally unique lowercase public username.';
COMMENT ON COLUMN identity.users.display_name IS 'User-facing display name not used for identity matching.';
COMMENT ON COLUMN identity.users.password_hash IS 'Reserved optional password verifier for future password login.';
COMMENT ON COLUMN identity.users.role IS 'Base authorization role: USER, ADMIN, or SYS_ADMIN.';
COMMENT ON COLUMN identity.users.status IS 'Account lifecycle state: ACTIVE, SUSPENDED, or REMOVED.';
COMMENT ON COLUMN identity.users.email_verified_at IS 'Time the current email address was verified.';
COMMENT ON COLUMN identity.users.auth_version IS 'Version incremented to invalidate active authentication sessions.';
COMMENT ON COLUMN identity.users.profile IS 'Public descriptive profile properties validated by the API.';
COMMENT ON COLUMN identity.users.settings IS 'Private user preferences validated by the API.';
COMMENT ON COLUMN identity.users.last_login_at IS 'Most recent successful authentication time.';
COMMENT ON COLUMN identity.users.created_at IS 'Account creation time.';
COMMENT ON COLUMN identity.users.updated_at IS 'Last account or profile update time maintained by trigger.';
COMMENT ON COLUMN identity.oauth_identities.id IS 'UUIDv7 OAuth identity primary key.';
COMMENT ON COLUMN identity.oauth_identities.user_id IS 'Owning local user account.';
COMMENT ON COLUMN identity.oauth_identities.provider IS 'External authentication provider currently limited to GITHUB.';
COMMENT ON COLUMN identity.oauth_identities.provider_user_id IS 'Stable provider-side subject identifier.';
COMMENT ON COLUMN identity.oauth_identities.provider_login IS 'Latest provider username or login for display.';
COMMENT ON COLUMN identity.oauth_identities.profile IS 'Last normalized public provider profile snapshot.';
COMMENT ON COLUMN identity.oauth_identities.created_at IS 'Time the provider identity was linked.';
COMMENT ON COLUMN identity.oauth_identities.updated_at IS 'Last provider identity refresh time.';

-- +goose Down
DROP SCHEMA directory CASCADE;
DROP SCHEMA identity CASCADE;
