-- +goose Up
CREATE TABLE identity.api_clients (
    id uuid PRIMARY KEY DEFAULT uuidv7(), -- UUIDv7 machine-client primary key generated by PostgreSQL.
    name text NOT NULL, -- Trimmed operator-facing client name.
    description text NOT NULL DEFAULT '', -- Optional trimmed operator-facing purpose description.
    audience text NOT NULL, -- Credential audience: INTERNAL or EXTERNAL.
    disabled_at timestamptz, -- Time all credentials for the client were disabled.
    created_by uuid NOT NULL REFERENCES identity.users(id), -- SYS_ADMIN user that created the client.
    created_at timestamptz NOT NULL DEFAULT now(), -- Time the client was created.
    updated_at timestamptz NOT NULL DEFAULT now(), -- Last client metadata or status update time.
    CONSTRAINT api_clients_name_check CHECK (
        name = btrim(name) AND name <> '' AND char_length(name) <= 128
    ),
    CONSTRAINT api_clients_description_check CHECK (
        description = btrim(description) AND char_length(description) <= 512
    ),
    CONSTRAINT api_clients_audience_check CHECK (audience IN ('INTERNAL', 'EXTERNAL')),
    CONSTRAINT api_clients_disabled_at_check CHECK (
        disabled_at IS NULL OR disabled_at >= created_at
    )
);
CREATE UNIQUE INDEX api_clients_name_unique_idx ON identity.api_clients (lower(name));
CREATE TRIGGER api_clients_touch_updated_at
BEFORE UPDATE ON identity.api_clients
FOR EACH ROW EXECUTE FUNCTION identity.touch_updated_at();

CREATE TABLE identity.api_client_scopes (
    client_id uuid NOT NULL REFERENCES identity.api_clients(id) ON DELETE CASCADE, -- Client receiving the scope.
    scope text NOT NULL, -- Explicit machine permission granted to the client.
    created_at timestamptz NOT NULL DEFAULT now(), -- Time the scope was granted.
    CONSTRAINT api_client_scopes_scope_check CHECK (
        scope IN ('data_import.write', 'sites.read')
    ),
    CONSTRAINT api_client_scopes_primary_key PRIMARY KEY (client_id, scope)
);

CREATE TABLE identity.api_keys (
    id uuid PRIMARY KEY DEFAULT uuidv7(), -- UUIDv7 API key record identifier.
    client_id uuid NOT NULL REFERENCES identity.api_clients(id), -- Machine client authenticated by this key.
    public_id text NOT NULL UNIQUE, -- Non-secret identifier encoded in the presented credential.
    key_prefix text NOT NULL, -- Short non-secret prefix shown in management interfaces.
    secret_hash bytea NOT NULL, -- SHA-256 digest of the 256-bit random secret.
    expires_at timestamptz, -- Credential expiry; required and capped for INTERNAL clients.
    last_used_at timestamptz, -- Approximate most recent successful authentication time.
    rotated_from_id uuid REFERENCES identity.api_keys(id), -- Previous key replaced by this credential.
    created_by uuid NOT NULL REFERENCES identity.users(id), -- SYS_ADMIN user that created the key.
    revoked_at timestamptz, -- Time the key was explicitly revoked.
    revoked_by uuid REFERENCES identity.users(id), -- SYS_ADMIN user that revoked the key.
    created_at timestamptz NOT NULL DEFAULT now(), -- Time the key was created.
    CONSTRAINT api_keys_public_id_check CHECK (public_id ~ '^[A-Za-z0-9_-]{12}$'),
    CONSTRAINT api_keys_prefix_check CHECK (key_prefix ~ '^hbk_[A-Za-z0-9_-]{12}_[A-Za-z0-9_-]{3}$'),
    CONSTRAINT api_keys_secret_hash_check CHECK (octet_length(secret_hash) = 32),
    CONSTRAINT api_keys_expiry_check CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT api_keys_last_used_at_check CHECK (last_used_at IS NULL OR last_used_at >= created_at),
    CONSTRAINT api_keys_rotation_check CHECK (rotated_from_id IS NULL OR rotated_from_id <> id),
    CONSTRAINT api_keys_revocation_check CHECK (
        (revoked_at IS NULL AND revoked_by IS NULL)
        OR (revoked_at IS NOT NULL AND revoked_by IS NOT NULL AND revoked_at >= created_at)
    )
);
CREATE UNIQUE INDEX api_keys_secret_hash_unique_idx ON identity.api_keys (secret_hash);
CREATE UNIQUE INDEX api_keys_rotated_from_unique_idx
ON identity.api_keys (rotated_from_id)
WHERE rotated_from_id IS NOT NULL;
CREATE INDEX api_keys_client_created_idx ON identity.api_keys (client_id, created_at DESC);

-- +goose StatementBegin
CREATE FUNCTION identity.enforce_api_key_expiration()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    client_audience text;
BEGIN
    SELECT audience INTO STRICT client_audience
      FROM identity.api_clients
     WHERE id = NEW.client_id;

    IF client_audience = 'INTERNAL' AND (
        NEW.expires_at IS NULL
        OR NEW.expires_at > NEW.created_at + interval '90 days'
    ) THEN
        RAISE EXCEPTION 'internal API keys must expire within ninety days'
            USING ERRCODE = '23514', CONSTRAINT = 'api_keys_internal_expiry_check';
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER api_keys_enforce_expiration
BEFORE INSERT OR UPDATE OF client_id, expires_at ON identity.api_keys
FOR EACH ROW EXECUTE FUNCTION identity.enforce_api_key_expiration();

GRANT SELECT, INSERT, UPDATE ON identity.api_clients TO api_runtime;
GRANT SELECT, INSERT, DELETE ON identity.api_client_scopes TO api_runtime;
GRANT SELECT, INSERT, UPDATE ON identity.api_keys TO api_runtime;

COMMENT ON TABLE identity.api_clients IS 'Machine clients that own scoped internal or external API credentials.';
COMMENT ON TABLE identity.api_client_scopes IS 'Explicit machine permissions assigned to API clients.';
COMMENT ON TABLE identity.api_keys IS 'Hashed, revocable API credentials issued to machine clients.';
COMMENT ON FUNCTION identity.enforce_api_key_expiration() IS 'Requires INTERNAL API keys to expire no later than ninety days after creation.';
COMMENT ON TRIGGER api_clients_touch_updated_at ON identity.api_clients IS 'Maintains the API client updated_at timestamp.';
COMMENT ON TRIGGER api_keys_enforce_expiration ON identity.api_keys IS 'Enforces the INTERNAL credential lifetime policy.';

COMMENT ON COLUMN identity.api_clients.id IS 'UUIDv7 machine-client primary key generated by PostgreSQL.';
COMMENT ON COLUMN identity.api_clients.name IS 'Trimmed operator-facing client name.';
COMMENT ON COLUMN identity.api_clients.description IS 'Optional trimmed operator-facing purpose description.';
COMMENT ON COLUMN identity.api_clients.audience IS 'Credential audience: INTERNAL or EXTERNAL.';
COMMENT ON COLUMN identity.api_clients.disabled_at IS 'Time all credentials for the client were disabled.';
COMMENT ON COLUMN identity.api_clients.created_by IS 'SYS_ADMIN user that created the client.';
COMMENT ON COLUMN identity.api_clients.created_at IS 'Time the client was created.';
COMMENT ON COLUMN identity.api_clients.updated_at IS 'Last client metadata or status update time.';
COMMENT ON COLUMN identity.api_client_scopes.client_id IS 'Client receiving the scope.';
COMMENT ON COLUMN identity.api_client_scopes.scope IS 'Explicit machine permission granted to the client.';
COMMENT ON COLUMN identity.api_client_scopes.created_at IS 'Time the scope was granted.';
COMMENT ON COLUMN identity.api_keys.id IS 'UUIDv7 API key record identifier.';
COMMENT ON COLUMN identity.api_keys.client_id IS 'Machine client authenticated by this key.';
COMMENT ON COLUMN identity.api_keys.public_id IS 'Non-secret identifier encoded in the presented credential.';
COMMENT ON COLUMN identity.api_keys.key_prefix IS 'Short non-secret prefix shown in management interfaces.';
COMMENT ON COLUMN identity.api_keys.secret_hash IS 'SHA-256 digest of the 256-bit random secret.';
COMMENT ON COLUMN identity.api_keys.expires_at IS 'Credential expiry; required and capped for INTERNAL clients.';
COMMENT ON COLUMN identity.api_keys.last_used_at IS 'Approximate most recent successful authentication time.';
COMMENT ON COLUMN identity.api_keys.rotated_from_id IS 'Previous key replaced by this credential.';
COMMENT ON COLUMN identity.api_keys.created_by IS 'SYS_ADMIN user that created the key.';
COMMENT ON COLUMN identity.api_keys.revoked_at IS 'Time the key was explicitly revoked.';
COMMENT ON COLUMN identity.api_keys.revoked_by IS 'SYS_ADMIN user that revoked the key.';
COMMENT ON COLUMN identity.api_keys.created_at IS 'Time the key was created.';

-- +goose Down
REVOKE ALL ON identity.api_keys FROM api_runtime;
REVOKE ALL ON identity.api_client_scopes FROM api_runtime;
REVOKE ALL ON identity.api_clients FROM api_runtime;
DROP TRIGGER api_keys_enforce_expiration ON identity.api_keys;
DROP FUNCTION identity.enforce_api_key_expiration();
DROP TABLE identity.api_keys;
DROP TABLE identity.api_client_scopes;
DROP TRIGGER api_clients_touch_updated_at ON identity.api_clients;
DROP TABLE identity.api_clients;
